/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/cnych/controller-demo/pkg/apis/stable/v1beta1"
	scheme "github.com/cnych/controller-demo/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CronTabsGetter has a method to return a CronTabInterface.
// A group's client should implement this interface.
type CronTabsGetter interface {
	CronTabs(namespace string) CronTabInterface
}

// CronTabInterface has methods to work with CronTab resources.
type CronTabInterface interface {
	Create(*v1beta1.CronTab) (*v1beta1.CronTab, error)
	Update(*v1beta1.CronTab) (*v1beta1.CronTab, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.CronTab, error)
	List(opts v1.ListOptions) (*v1beta1.CronTabList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.CronTab, err error)
	CronTabExpansion
}

// cronTabs implements CronTabInterface
type cronTabs struct {
	client rest.Interface
	ns     string
}

// newCronTabs returns a CronTabs
func newCronTabs(c *StableV1beta1Client, namespace string) *cronTabs {
	return &cronTabs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cronTab, and returns the corresponding cronTab object, and an error if there is any.
func (c *cronTabs) Get(name string, options v1.GetOptions) (result *v1beta1.CronTab, err error) {
	result = &v1beta1.CronTab{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crontabs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CronTabs that match those selectors.
func (c *cronTabs) List(opts v1.ListOptions) (result *v1beta1.CronTabList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.CronTabList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crontabs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cronTabs.
func (c *cronTabs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("crontabs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cronTab and creates it.  Returns the server's representation of the cronTab, and an error, if there is any.
func (c *cronTabs) Create(cronTab *v1beta1.CronTab) (result *v1beta1.CronTab, err error) {
	result = &v1beta1.CronTab{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("crontabs").
		Body(cronTab).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cronTab and updates it. Returns the server's representation of the cronTab, and an error, if there is any.
func (c *cronTabs) Update(cronTab *v1beta1.CronTab) (result *v1beta1.CronTab, err error) {
	result = &v1beta1.CronTab{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("crontabs").
		Name(cronTab.Name).
		Body(cronTab).
		Do().
		Into(result)
	return
}

// Delete takes name of the cronTab and deletes it. Returns an error if one occurs.
func (c *cronTabs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crontabs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cronTabs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crontabs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cronTab.
func (c *cronTabs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.CronTab, err error) {
	result = &v1beta1.CronTab{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("crontabs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
